//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticuloPresentacion
    {
        public System.Guid ArticuloPresentacion_Id { get; set; }
        public System.Guid Presentacion_Id { get; set; }
        public decimal Cantidad { get; set; }
        public string Preposicion { get; set; }
        public System.Guid UnidadPresentacion_Id { get; set; }
        public int Activo { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual Presentacion Presentacion { get; set; }
        public virtual UnidadPresentacion UnidadPresentacion { get; set; }
    }
}
