//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutorizacionLimites
    {
        public int ClavePrograma { get; set; }
        public int ClaveTipoFuncionPrograma { get; set; }
        public decimal Limite { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual Programa Programa { get; set; }
        public virtual TipoFuncionPrograma TipoFuncionPrograma { get; set; }
    }
}
