//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraExcepciones
    {
        public int ClaveSucursal { get; set; }
        public int Ticket { get; set; }
        public short ClaveTipoError { get; set; }
        public string CodigoError { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Origen { get; set; }
        public string Funcion { get; set; }
        public string Pantalla { get; set; }
        public string Observaciones { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual TipoError TipoError { get; set; }
    }
}
