//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraFacturaCFD
    {
        public System.Guid BitacoraFacturaCFD_Id { get; set; }
        public System.Guid FacturaCFD_Id { get; set; }
        public System.Guid SesionUsuario_Id { get; set; }
        public int Estatus { get; set; }
        public string Parametros { get; set; }
        public string Resultado { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public int UsuarioAlta { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
    
        public virtual FacturaClienteCFD FacturaClienteCFD { get; set; }
    }
}
