//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraPrograma
    {
        public int ClaveBitacoraPrograma { get; set; }
        public string NombreMaquina { get; set; }
        public string MAC { get; set; }
        public string Programa { get; set; }
        public string CodigoUsuario { get; set; }
        public Nullable<System.DateTime> HoraEntrada { get; set; }
        public Nullable<System.DateTime> HoraSalida { get; set; }
    }
}
