//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraCancelacionesPendientes
    {
        public System.Guid BitacoraCancelacionesPendientesId { get; set; }
        public System.Guid ClienteId { get; set; }
        public int NumeroCliente { get; set; }
        public string NombreCliente { get; set; }
        public System.Guid DocumentoId { get; set; }
        public string Documento { get; set; }
        public System.DateTime FechaDocumento { get; set; }
        public int Estatus { get; set; }
        public string DescripcionError { get; set; }
        public Nullable<System.DateTime> FechaUltimaActualizacion { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    }
}
