//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraClienteCreditoExcedente
    {
        public System.Guid ClienteCredito_Id { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public decimal ImporteExcedente { get; set; }
        public int UsuarioAutorizaExcedente { get; set; }
    
        public virtual ClienteCredito ClienteCredito { get; set; }
    }
}
