//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteAvisoPago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClienteAvisoPago()
        {
            this.ClienteAvisoPagoDetalle = new HashSet<ClienteAvisoPagoDetalle>();
        }
    
        public System.Guid ClienteAvisoPago_Id { get; set; }
        public System.Guid Cliente_Id { get; set; }
        public string SerieAvisoPago { get; set; }
        public int FolioAvisoPago { get; set; }
        public System.Guid CuentaBancariaDSA_Id { get; set; }
        public decimal ImporteDeposito { get; set; }
        public short ClaveTipoFormaPago { get; set; }
        public System.DateTime FechaDeposito { get; set; }
        public Nullable<int> ClaveBacoOrigen { get; set; }
        public string Referencia { get; set; }
        public int ClaveTipoMoneda { get; set; }
        public int Estatus { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual Banco Banco { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual CuentaBancariaDSA CuentaBancariaDSA { get; set; }
        public virtual TipoFormaPago TipoFormaPago { get; set; }
        public virtual TipoMoneda TipoMoneda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClienteAvisoPagoDetalle> ClienteAvisoPagoDetalle { get; set; }
    }
}
