//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteContactoCorreo
    {
        public System.Guid ClienteContactoCorreo_Id { get; set; }
        public System.Guid ClienteContacto_Id { get; set; }
        public int ClaveTipoCorreo { get; set; }
        public string CorreoElectronico { get; set; }
        public bool Activo { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual ClienteContacto ClienteContacto { get; set; }
        public virtual TipoCorreo TipoCorreo { get; set; }
    }
}
