//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteAbcActualizacion
    {
        public int ClaveCliente { get; set; }
        public string ABC1 { get; set; }
        public string ABC2 { get; set; }
        public string ABC3 { get; set; }
    }
}
