//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteDescripcion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClienteDescripcion()
        {
            this.ClienteDescripcionDetalle = new HashSet<ClienteDescripcionDetalle>();
        }
    
        public System.Guid ClienteDescripcion_Id { get; set; }
        public System.Guid Cliente_Id { get; set; }
        public string Descripcion { get; set; }
        public string NotaClienteDescripcion { get; set; }
        public int OpcEstatusDescripcionCliente { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClienteDescripcionDetalle> ClienteDescripcionDetalle { get; set; }
    }
}
