//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteDireccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClienteDireccion()
        {
            this.ClienteCalendario = new HashSet<ClienteCalendario>();
            this.ClienteContacto = new HashSet<ClienteContacto>();
        }
    
        public System.Guid ClienteDireccion_Id { get; set; }
        public System.Guid Cliente_Id { get; set; }
        public short ClaveTipoVialidad { get; set; }
        public int ClaveTipoDireccion { get; set; }
        public bool DireccionPrincipal { get; set; }
        public int ClaveColonia { get; set; }
        public string Calle { get; set; }
        public string NumeroExterno { get; set; }
        public string NumeroInterno { get; set; }
        public string EntreCalles { get; set; }
        public string Observacion { get; set; }
        public bool Activo { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public int Estatus { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClienteCalendario> ClienteCalendario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClienteContacto> ClienteContacto { get; set; }
        public virtual Colonia Colonia { get; set; }
        public virtual TipoDireccion TipoDireccion { get; set; }
        public virtual TipoVialidad TipoVialidad { get; set; }
    }
}
