//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteSolicitudCheque
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClienteSolicitudCheque()
        {
            this.ClienteCheque = new HashSet<ClienteCheque>();
            this.SolicitudChequeEstatus = new HashSet<SolicitudChequeEstatus>();
            this.SolicitudChequeRequisitoSeguimiento = new HashSet<SolicitudChequeRequisitoSeguimiento>();
        }
    
        public System.Guid SolicitudCheque_Id { get; set; }
        public System.Guid Cliente_Id { get; set; }
        public string SerieSolicitudCheque { get; set; }
        public int FolioSolicitudCheque { get; set; }
        public int ClaveSucursalEmiteSolicitud { get; set; }
        public int OpcTipoSolicitud { get; set; }
        public int ClaveSolicitudChequeEstatus { get; set; }
        public string NombreSolicitante { get; set; }
        public string PuestoSolicitante { get; set; }
        public string TelefonoSolicitante { get; set; }
        public string CorreoSolicitante { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClienteCheque> ClienteCheque { get; set; }
        public virtual SolicitudChequeSeguimientoEstatus SolicitudChequeSeguimientoEstatus { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudChequeEstatus> SolicitudChequeEstatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudChequeRequisitoSeguimiento> SolicitudChequeRequisitoSeguimiento { get; set; }
    }
}
