//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteCondicionVenta
    {
        public System.Guid Cliente_Id { get; set; }
        public short ClaveCondicionVenta { get; set; }
        public Nullable<bool> Activa { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual CondicionVenta CondicionVenta { get; set; }
    }
}
