//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteContacto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClienteContacto()
        {
            this.ClienteContactoCorreo = new HashSet<ClienteContactoCorreo>();
            this.ClienteContactoTelefono = new HashSet<ClienteContactoTelefono>();
            this.CotizacionCliente = new HashSet<CotizacionCliente>();
            this.CotizacionClienteHojaTrabajo = new HashSet<CotizacionClienteHojaTrabajo>();
        }
    
        public System.Guid ClienteContacto_Id { get; set; }
        public System.Guid Cliente_Id { get; set; }
        public Nullable<System.Guid> ClienteDireccion_Id { get; set; }
        public string Nombre1 { get; set; }
        public string Nombre2 { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public short ClaveTipoContacto { get; set; }
        public string Puesto { get; set; }
        public int Activo { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<System.DateTime> FechaUltimoContacto { get; set; }
        public Nullable<int> ClaveCanalVenta { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string CodigoPostal { get; set; }
        public string NombreLargo { get; set; }
        public int AceptaContacto { get; set; }
        public int Genero { get; set; }
    
        public virtual CanalVenta CanalVenta { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual ClienteDireccion ClienteDireccion { get; set; }
        public virtual TipoContacto TipoContacto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClienteContactoCorreo> ClienteContactoCorreo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClienteContactoTelefono> ClienteContactoTelefono { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CotizacionCliente> CotizacionCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CotizacionClienteHojaTrabajo> CotizacionClienteHojaTrabajo { get; set; }
    }
}
