//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteDocumentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClienteDocumentos()
        {
            this.SolicitudChequeRequisitoSeguimiento = new HashSet<SolicitudChequeRequisitoSeguimiento>();
            this.SolicitudCreditoRequisitoSeguimiento = new HashSet<SolicitudCreditoRequisitoSeguimiento>();
        }
    
        public System.Guid ClienteDocumento_Id { get; set; }
        public System.Guid Cliente_Id { get; set; }
        public int ClaveTipoDocumentoCliente { get; set; }
        public byte[] Archivo { get; set; }
        public string NombreArchivo { get; set; }
        public int ClaveEstatus { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public int UsuarioAlta { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual TipoDocumentoCliente TipoDocumentoCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudChequeRequisitoSeguimiento> SolicitudChequeRequisitoSeguimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudCreditoRequisitoSeguimiento> SolicitudCreditoRequisitoSeguimiento { get; set; }
    }
}
