//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlReimpresion
    {
        public System.Guid ControlReimpresion_Id { get; set; }
        public int ClaveSucursal { get; set; }
        public int OpcCausaReimpresion { get; set; }
        public int ClaveTipoDocumento { get; set; }
        public int ClaveSucursalDocumento { get; set; }
        public string SerieDocumento { get; set; }
        public int FolioDocumento { get; set; }
        public System.DateTime FechaReImpresion { get; set; }
        public int OpcEstatusReimpresion { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual Sucursal Sucursal { get; set; }
        public virtual TipoDocumento TipoDocumento { get; set; }
    }
}
