//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlEventoDetalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ControlEventoDetalle()
        {
            this.ControlEventoFolioAsignado = new HashSet<ControlEventoFolioAsignado>();
        }
    
        public System.Guid EventoDetalle_Id { get; set; }
        public System.Guid Evento_Id { get; set; }
        public System.Guid Factura_Id { get; set; }
        public System.Guid Cliente_Id { get; set; }
        public int ClaveSucursalFactura { get; set; }
        public int ClaveSucursalAlta { get; set; }
        public string SerieFactura { get; set; }
        public int FolioFactura { get; set; }
        public string Nombre1 { get; set; }
        public string Nombre2 { get; set; }
        public string ApPaterno { get; set; }
        public string ApMaterno { get; set; }
        public string Correo { get; set; }
        public Nullable<int> TipoTelefono { get; set; }
        public string Telefono { get; set; }
        public string Puesto { get; set; }
        public decimal ImporteTotal { get; set; }
        public string Notas { get; set; }
        public int NumeroBoletos { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<int> UsuarioAutoriza { get; set; }
        public Nullable<System.DateTime> FechaAutotiza { get; set; }
    
        public virtual ControlEvento ControlEvento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlEventoFolioAsignado> ControlEventoFolioAsignado { get; set; }
    }
}
