//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlEventoFolio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ControlEventoFolio()
        {
            this.ControlEventoFolioAsignado = new HashSet<ControlEventoFolioAsignado>();
        }
    
        public System.Guid Evento_Id { get; set; }
        public System.Guid BloqueFolio_Id { get; set; }
        public int UsuarioAsignado { get; set; }
        public int FolioInicial { get; set; }
        public int FolioFinal { get; set; }
        public int FolioActual { get; set; }
        public int SucursalAlta { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
    
        public virtual ControlEvento ControlEvento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlEventoFolioAsignado> ControlEventoFolioAsignado { get; set; }
    }
}
