//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaXPagar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuentaXPagar()
        {
            this.ProcesoPagoCxPDetalle = new HashSet<ProcesoPagoCxPDetalle>();
            this.CuentaXPagarComprobante = new HashSet<CuentaXPagarComprobante>();
            this.CuentaXPagarFactoraje = new HashSet<CuentaXPagarFactoraje>();
            this.CuentaXPagarFactoraje1 = new HashSet<CuentaXPagarFactoraje>();
            this.MovimientoCuentaxPagar = new HashSet<MovimientoCuentaxPagar>();
        }
    
        public System.Guid CuentaPorPagar_Id { get; set; }
        public System.Guid ProveedorAcreedor_Id { get; set; }
        public int ClaveCuentaXPagar { get; set; }
        public string SerieDocumentoOrigen { get; set; }
        public Nullable<int> FolioDocumentoOrigen { get; set; }
        public Nullable<int> ClaveTipoDocumentoXML { get; set; }
        public string SerieXML { get; set; }
        public string FolioXML { get; set; }
        public Nullable<int> FolioIngreso { get; set; }
        public string Referencia { get; set; }
        public System.DateTime FechaRecibeOperacion { get; set; }
        public System.DateTime FechaOperacion { get; set; }
        public Nullable<System.DateTime> FechaProgramacionPago { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public int DiasCredito { get; set; }
        public decimal DescuentoFinanciero { get; set; }
        public string FolioPublicacion { get; set; }
        public int ClaveTipoMoneda { get; set; }
        public int ClaveSucursal { get; set; }
        public decimal FactorCambiarioOrigen { get; set; }
        public decimal FactorCambiarioActualizado { get; set; }
        public Nullable<System.DateTime> FechaTipoCambioActualizado { get; set; }
        public System.Guid Origen_Id { get; set; }
        public int ClaveOrigen { get; set; }
        public decimal ImporteSubTotal { get; set; }
        public decimal ImporteIVA { get; set; }
        public decimal PorcentajeIVA { get; set; }
        public Nullable<decimal> PorcentajeIVACalculado { get; set; }
        public decimal ImporteTotal { get; set; }
        public decimal ImporteAplicado { get; set; }
        public decimal ImporteSubTotalMx { get; set; }
        public decimal ImporteIVAMx { get; set; }
        public decimal ImporteTotalMx { get; set; }
        public decimal Saldo { get; set; }
        public decimal ImporteAnticipoAplicado { get; set; }
        public decimal ImporteAjusteCambiario { get; set; }
        public int Visible { get; set; }
        public int ClaveEstatusCuentaPorPagar { get; set; }
        public Nullable<System.Guid> SesionUsuario_Id { get; set; }
        public Nullable<int> UsuarioCancela { get; set; }
        public Nullable<System.DateTime> FechaCancela { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcesoPagoCxPDetalle> ProcesoPagoCxPDetalle { get; set; }
        public virtual ProveedorAcreedor ProveedorAcreedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentaXPagarComprobante> CuentaXPagarComprobante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentaXPagarFactoraje> CuentaXPagarFactoraje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentaXPagarFactoraje> CuentaXPagarFactoraje1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovimientoCuentaxPagar> MovimientoCuentaxPagar { get; set; }
    }
}
