//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaCobrarCliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuentaCobrarCliente()
        {
            this.BitacoraCuentaCobrar = new HashSet<BitacoraCuentaCobrar>();
            this.CobranzaClienteDetalle = new HashSet<CobranzaClienteDetalle>();
            this.CuentaCobrarClienteMovimiento = new HashSet<CuentaCobrarClienteMovimiento>();
            this.RevisionClienteDetalle = new HashSet<RevisionClienteDetalle>();
        }
    
        public System.Guid CuentaCobrarCliente_Id { get; set; }
        public System.Guid Cliente_Id { get; set; }
        public string CodigoDocumentoFiscalOrigen { get; set; }
        public string SerieDocumentoOrigen { get; set; }
        public Nullable<int> FolioDocumentoOrigen { get; set; }
        public Nullable<System.Guid> FacturaCliente_Id { get; set; }
        public Nullable<System.Guid> NotaCargo_Id { get; set; }
        public Nullable<System.Guid> FacturaEspecial_Id { get; set; }
        public Nullable<System.DateTime> FechaRecibeCredito { get; set; }
        public Nullable<System.DateTime> FechaProgramadaRevision { get; set; }
        public Nullable<System.DateTime> FechaRevision { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public Nullable<System.DateTime> FechaEmitioDocumento { get; set; }
        public Nullable<System.DateTime> FechaVenceCuentaCobrar { get; set; }
        public Nullable<System.DateTime> FechaProgramadaCobranza { get; set; }
        public Nullable<System.DateTime> FechaCobranza { get; set; }
        public Nullable<System.DateTime> FechaRecibeCreditoDeCobranza { get; set; }
        public int DiasCredito { get; set; }
        public Nullable<short> ClaveTipoCredito { get; set; }
        public short ClaveTipoFormaPago { get; set; }
        public int ClaveTipoMoneda { get; set; }
        public short ClaveCondicionVenta { get; set; }
        public Nullable<int> ClaveTipoCambio { get; set; }
        public int ClaveSucursal { get; set; }
        public decimal ValorTipoCambio { get; set; }
        public decimal ImporteVenta { get; set; }
        public decimal ImporteTotal { get; set; }
        public decimal ImporteAplicado { get; set; }
        public decimal Saldo { get; set; }
        public decimal ImporteAnticipo { get; set; }
        public decimal ImporteAnticipoAplicado { get; set; }
        public decimal ImporteBonificacion { get; set; }
        public int Visible { get; set; }
        public int ClaveTipoMovimientoCuentaPorCobrar { get; set; }
        public Nullable<int> EstatusClienteCuentaCobrar { get; set; }
        public int ClaveEstatusCobranza { get; set; }
        public Nullable<System.Guid> SesionCaja_Id { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BitacoraCuentaCobrar> BitacoraCuentaCobrar { get; set; }
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CobranzaClienteDetalle> CobranzaClienteDetalle { get; set; }
        public virtual CondicionVenta CondicionVenta { get; set; }
        public virtual EstatusCobranza EstatusCobranza { get; set; }
        public virtual FacturaCliente FacturaCliente { get; set; }
        public virtual FacturaEspecial FacturaEspecial { get; set; }
        public virtual NotaCargo NotaCargo { get; set; }
        public virtual SesionCaja SesionCaja { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual TipoCambio TipoCambio { get; set; }
        public virtual TipoCredito TipoCredito { get; set; }
        public virtual TipoDocumentoFiscal TipoDocumentoFiscal { get; set; }
        public virtual TipoFormaPago TipoFormaPago { get; set; }
        public virtual TipoMoneda TipoMoneda { get; set; }
        public virtual TipoMovimientoCuentaPorCobrar TipoMovimientoCuentaPorCobrar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentaCobrarClienteMovimiento> CuentaCobrarClienteMovimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RevisionClienteDetalle> RevisionClienteDetalle { get; set; }
    }
}
