//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaCobrarClienteMovimiento
    {
        public System.Guid CuentaCobrarClienteMovimiento_Id { get; set; }
        public long FolioMovimiento { get; set; }
        public System.Guid Cliente_Id { get; set; }
        public Nullable<System.Guid> CuentaCobrarCliente_Id { get; set; }
        public Nullable<System.Guid> PagoCliente_Id { get; set; }
        public Nullable<System.Guid> PagoClienteDestino_Id { get; set; }
        public Nullable<System.Guid> SesionCaja_Id { get; set; }
        public int ClaveTipoMovimiento { get; set; }
        public int ClaveSucursal { get; set; }
        public System.DateTime FechaAplicoCuentaCobrar { get; set; }
        public decimal ImporteAnteriorFactura { get; set; }
        public decimal ImporteAnteriorPago { get; set; }
        public decimal ImporteAplicado { get; set; }
        public decimal ImporteAnticipoAplicado { get; set; }
        public decimal SaldoFactura { get; set; }
        public decimal SaldoPago { get; set; }
        public string NotaCuentaCobrarClienteMovimiento { get; set; }
        public string NotaCancelacion { get; set; }
        public int OpcEstatuCuentaCobrarClienteMovimiento { get; set; }
        public int Visible { get; set; }
        public Nullable<int> UsuarioAutorizaCancelar { get; set; }
        public Nullable<int> UsuarioAutorizaCancelar2 { get; set; }
        public Nullable<System.DateTime> FechaCancela { get; set; }
        public Nullable<int> UsuarioAutoriza { get; set; }
        public Nullable<System.DateTime> FechaAutoriza { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual CuentaCobrarCliente CuentaCobrarCliente { get; set; }
        public virtual PagoCliente PagoCliente { get; set; }
        public virtual SesionCaja SesionCaja { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual TipoMovimientoCuentaPorCobrar TipoMovimientoCuentaPorCobrar { get; set; }
    }
}
