//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Descuentos
    {
        public int ClaveDescuento { get; set; }
        public short ClaveTipoDescuento { get; set; }
        public decimal Porcentaje { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> ImporteMinimo { get; set; }
        public Nullable<decimal> ImporteMaximo { get; set; }
        public bool Activo { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual TipoDescuento TipoDescuento { get; set; }
    }
}
