//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevolucionClienteProducto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DevolucionClienteProducto()
        {
            this.DevolucionClienteProductoImporte = new HashSet<DevolucionClienteProductoImporte>();
        }
    
        public System.Guid DevolucionCliente_Id { get; set; }
        public int NumeroPartidaOrigen { get; set; }
        public Nullable<int> ClaveTipoCausaDevolucion { get; set; }
        public Nullable<System.Guid> SeccionProductoIDOrigen { get; set; }
        public Nullable<System.Guid> SeccionProductoIDDestino { get; set; }
        public int CantidadDevuelta { get; set; }
        public string GrupoVentaABC { get; set; }
        public decimal PrecioCreditoOrigen { get; set; }
        public decimal PrecioLista { get; set; }
        public decimal PrecioVenta { get; set; }
        public Nullable<int> ClaveTipoMonedaOrigen { get; set; }
        public Nullable<int> ClaveTipoMonedaDestino { get; set; }
        public decimal FactorTipoCambio { get; set; }
        public int ExistenciaMinima { get; set; }
        public int ExistenciaMaxima { get; set; }
        public string DescripcionCliente1 { get; set; }
        public string DescripcionCliente2 { get; set; }
        public decimal CostoPromedioSalida { get; set; }
        public string ProductoTrameria { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual DevolucionCliente DevolucionCliente { get; set; }
        public virtual SeccionProducto SeccionProducto { get; set; }
        public virtual TipoCausaDevolucionCliente TipoCausaDevolucionCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DevolucionClienteProductoImporte> DevolucionClienteProductoImporte { get; set; }
    }
}
