//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dispositivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dispositivo()
        {
            this.DispositivoFiscal = new HashSet<DispositivoFiscal>();
            this.DispositivoServicio = new HashSet<DispositivoServicio>();
            this.Impresora = new HashSet<Impresora>();
            this.UsuarioSesion = new HashSet<UsuarioSesion>();
        }
    
        public long MAC { get; set; }
        public byte[] HEXADDRESS { get; set; }
        public Nullable<int> ClaveSucursal { get; set; }
        public Nullable<int> ClaveAlmacen { get; set; }
        public Nullable<int> ClaveSeccion { get; set; }
        public Nullable<int> ClaveUbicacion { get; set; }
        public string Configuracion { get; set; }
        public string NombreDispositivo { get; set; }
        public string Descripcion { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Serie { get; set; }
        public Nullable<long> DireccionIP { get; set; }
        public int Activo { get; set; }
        public Nullable<System.Guid> PerfilImpresion_Id { get; set; }
        public System.Guid TipoDispositivo_Id { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual PerfilImpresion PerfilImpresion { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual TipoDispositivo TipoDispositivo { get; set; }
        public virtual Ubicacion Ubicacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DispositivoFiscal> DispositivoFiscal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DispositivoServicio> DispositivoServicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Impresora> Impresora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioSesion> UsuarioSesion { get; set; }
    }
}
