//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DispositivoServicio
    {
        public long MAC { get; set; }
        public int ClaveTipoServicio { get; set; }
        public string Direccion { get; set; }
        public int Puerto { get; set; }
        public string EndPoint { get; set; }
        public string HostType { get; set; }
        public string ContractType { get; set; }
    
        public virtual Dispositivo Dispositivo { get; set; }
    }
}
