//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaClienteEquipo
    {
        public System.Guid FacturaCliente_Id { get; set; }
        public int ClaveTipoFuncionUsuario { get; set; }
        public int ClaveUsuarioEquipo { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public int UsuarioAlta { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
    
        public virtual FacturaCliente FacturaCliente { get; set; }
        public virtual TipoFuncionUsuario TipoFuncionUsuario { get; set; }
    }
}
