//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaEspecialDetalle
    {
        public System.Guid FacturaEspecial_Id { get; set; }
        public int ClaveFacturaEspecialPartida { get; set; }
        public string Concepto { get; set; }
        public string Descripcion1 { get; set; }
        public string CodigoUnidadFiscal { get; set; }
        public int Cantidad { get; set; }
        public decimal Precio { get; set; }
        public decimal Subtotal { get; set; }
        public decimal IVA { get; set; }
        public decimal PorcentajeIVA { get; set; }
        public decimal Total { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public decimal Venta { get; set; }
        public decimal PorcentajeDescuentoProntoPago { get; set; }
        public decimal DescuentoProntoPago { get; set; }
        public decimal PorcentajeDescuentoSegmento { get; set; }
        public decimal DescuentoSegmento { get; set; }
        public decimal PorcentajeDescuentoLogistica { get; set; }
        public decimal DescuentoLogistica { get; set; }
        public decimal PorcentajeDescuentoNotaCredito { get; set; }
        public decimal DescuentoNotaCredito { get; set; }
        public decimal PorcentajeDescuentoOperacion { get; set; }
        public decimal DescuentoOperacion { get; set; }
        public decimal PorcentajeDescuentoAnticipo { get; set; }
        public decimal DescuentoAnticipo { get; set; }
        public decimal PorcentajeDescuentoPromocion { get; set; }
        public decimal DescuentoPromocion { get; set; }
        public decimal PorcentajeSaldo { get; set; }
        public decimal Saldo { get; set; }
        public decimal PorcentajePaqueteria { get; set; }
        public decimal Paqueteria { get; set; }
        public decimal BaseIVA { get; set; }
    
        public virtual FacturaEspecial FacturaEspecial { get; set; }
    }
}
