//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaClienteCFD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FacturaClienteCFD()
        {
            this.BitacoraFacturaCFD = new HashSet<BitacoraFacturaCFD>();
            this.FacturaCFDBitacoraAcceso = new HashSet<FacturaCFDBitacoraAcceso>();
            this.FacturaCFDBitacoraTimbrado = new HashSet<FacturaCFDBitacoraTimbrado>();
        }
    
        public System.Guid FacturaCfdId { get; set; }
        public string CodigoDocumentoFiscal { get; set; }
        public int DS { get; set; }
        public string CadenaOriginal { get; set; }
        public byte[] SelloDigital { get; set; }
        public string CuentaPago { get; set; }
        public Nullable<int> ClaveFormaPagoSat { get; set; }
        public string MetodoPago { get; set; }
        public Nullable<int> SolicitudTimbrado { get; set; }
        public decimal Version { get; set; }
        public string CodigoRecuperacion { get; set; }
        public Nullable<System.Guid> AcuseCancelacion { get; set; }
        public Nullable<System.Guid> ArchivoAddendaId { get; set; }
        public Nullable<System.Guid> ArchivoPdfId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BitacoraFacturaCFD> BitacoraFacturaCFD { get; set; }
        public virtual ComplementoPagoCliente ComplementoPagoCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturaCFDBitacoraAcceso> FacturaCFDBitacoraAcceso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturaCFDBitacoraTimbrado> FacturaCFDBitacoraTimbrado { get; set; }
        public virtual FacturaCliente FacturaCliente { get; set; }
        public virtual FormaPagoSAT FormaPagoSAT { get; set; }
        public virtual TipoDocumentoFiscal TipoDocumentoFiscal { get; set; }
        public virtual FacturaClienteCFDI FacturaClienteCFDI { get; set; }
        public virtual FacturaEspecial FacturaEspecial { get; set; }
        public virtual NotaCargo NotaCargo { get; set; }
        public virtual NotaCredito NotaCredito { get; set; }
        public virtual ValeInterAlmacen ValeInterAlmacen { get; set; }
    }
}
