//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaCliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FacturaCliente()
        {
            this.AnticipoCliente = new HashSet<AnticipoCliente>();
            this.CuentaCobrarCliente = new HashSet<CuentaCobrarCliente>();
            this.FacturaCliente1 = new HashSet<FacturaCliente>();
            this.FacturaClienteEquipo = new HashSet<FacturaClienteEquipo>();
            this.FacturaClienteImportes = new HashSet<FacturaClienteImportes>();
            this.SesionFacturaEntregaDetalle = new HashSet<SesionFacturaEntregaDetalle>();
            this.TrackingOrdenDespacho = new HashSet<TrackingOrdenDespacho>();
        }
    
        public System.Guid FacturaCliente_Id { get; set; }
        public string SerieFactura { get; set; }
        public int FolioFactura { get; set; }
        public Nullable<System.Guid> SesionCaja_Id { get; set; }
        public int ClaveSucursal { get; set; }
        public int ClaveTipoFactura { get; set; }
        public Nullable<System.Guid> OrdenDespachoId { get; set; }
        public Nullable<int> ClaveOrdenDespachoSucursal { get; set; }
        public Nullable<int> ClaveOrdenDespacho { get; set; }
        public Nullable<short> ClaveCondicionVenta { get; set; }
        public Nullable<int> ClaveVendedor { get; set; }
        public Nullable<int> ClaveRepresentante { get; set; }
        public int ClaveTipoMoneda { get; set; }
        public decimal ValorTipoCambio { get; set; }
        public decimal Costo { get; set; }
        public decimal VentaNeta { get; set; }
        public decimal ImporteAnticipo { get; set; }
        public Nullable<int> OpcTipoIVA { get; set; }
        public Nullable<System.Guid> AnticipoCliente_Id { get; set; }
        public Nullable<System.Guid> CambioFactura_Id { get; set; }
        public Nullable<decimal> PorcentajeAnticipo { get; set; }
        public Nullable<System.Guid> ClienteCredito_Id { get; set; }
        public string ConceptoFactura { get; set; }
        public int OpcEstatusEntrega { get; set; }
        public Nullable<int> OpcEstatusRevision { get; set; }
        public Nullable<int> OpcEstatusCobraza { get; set; }
        public Nullable<int> OpcEstatusJuridico { get; set; }
        public int ClaveEstatusFactura { get; set; }
        public System.Guid Cliente_Id { get; set; }
        public Nullable<int> UsuarioCancela { get; set; }
        public Nullable<System.DateTime> FechaCancela { get; set; }
        public Nullable<int> UsuarioAutoriza { get; set; }
        public Nullable<System.DateTime> FechaAutoriza { get; set; }
        public Nullable<int> BanderaTipoImpresion { get; set; }
        public string Certificado { get; set; }
        public string AnioAprobacion { get; set; }
        public string NoAprobacion { get; set; }
        public Nullable<int> MovimientoFactura { get; set; }
        public Nullable<System.Guid> FacturaClienteAnterior_Id { get; set; }
        public Nullable<int> OpcTipoDevolucion { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public string RepartoPaqueteria { get; set; }
        public decimal CostoEnvio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnticipoCliente> AnticipoCliente { get; set; }
        public virtual AnticipoCliente AnticipoCliente1 { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual ClienteCredito ClienteCredito { get; set; }
        public virtual CondicionVenta CondicionVenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentaCobrarCliente> CuentaCobrarCliente { get; set; }
        public virtual EstatusFactura EstatusFactura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturaCliente> FacturaCliente1 { get; set; }
        public virtual FacturaCliente FacturaCliente2 { get; set; }
        public virtual FacturaClienteCFD FacturaClienteCFD { get; set; }
        public virtual OrdenDespacho OrdenDespacho { get; set; }
        public virtual SesionCaja SesionCaja { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual TipoFactura TipoFactura { get; set; }
        public virtual TipoMoneda TipoMoneda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturaClienteEquipo> FacturaClienteEquipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturaClienteImportes> FacturaClienteImportes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SesionFacturaEntregaDetalle> SesionFacturaEntregaDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrackingOrdenDespacho> TrackingOrdenDespacho { get; set; }
    }
}
