//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FolioFiscal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FolioFiscal()
        {
            this.DispositivoFiscal = new HashSet<DispositivoFiscal>();
        }
    
        public string ClaveFolioFiscal { get; set; }
        public int ClaveSucursal { get; set; }
        public string NumeroCertificado { get; set; }
        public string CodigoDocumentoFiscal { get; set; }
        public string Descripcion { get; set; }
        public string Serie { get; set; }
        public int FolioActual { get; set; }
        public int FolioInicial { get; set; }
        public int FolioFinal { get; set; }
        public int NumeroAprobacion { get; set; }
        public string AnioAprobacion { get; set; }
        public string Certificado { get; set; }
        public string Firma { get; set; }
        public bool Activo { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DispositivoFiscal> DispositivoFiscal { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual TipoDocumentoFiscal TipoDocumentoFiscal { get; set; }
    }
}
