//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FolioDocumento
    {
        public string Serie { get; set; }
        public int ClaveSucursal { get; set; }
        public string Documento { get; set; }
        public int Folio { get; set; }
        public string Descripcion { get; set; }
        public string Mascara { get; set; }
        public string MAC { get; set; }
        public Nullable<int> Grupo { get; set; }
    }
}
