//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrupoNotificacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GrupoNotificacion()
        {
            this.GrupoNotificacionEvento = new HashSet<GrupoNotificacionEvento>();
            this.GrupoNotificacionUsuario = new HashSet<GrupoNotificacionUsuario>();
        }
    
        public System.Guid GrupoNotificacion_Id { get; set; }
        public Nullable<System.Guid> Notificacion_Id { get; set; }
        public string Llave { get; set; }
        public int CSharpHash { get; set; }
        public int ClaveEventoEstatus { get; set; }
        public int Estatus { get; set; }
        public System.DateTime FechaUltimoEvento { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual Notificacion Notificacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GrupoNotificacionEvento> GrupoNotificacionEvento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GrupoNotificacionUsuario> GrupoNotificacionUsuario { get; set; }
    }
}
