//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrupoNotificacionUsuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GrupoNotificacionUsuario()
        {
            this.GrupoNotificacionConfirmacion = new HashSet<GrupoNotificacionConfirmacion>();
        }
    
        public System.Guid GrupoNotificacionUsuario_Id { get; set; }
        public System.Guid GrupoNotificacion_Id { get; set; }
        public int ClaveUsuario { get; set; }
        public string Parametros { get; set; }
        public int Estatus { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual GrupoNotificacion GrupoNotificacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GrupoNotificacionConfirmacion> GrupoNotificacionConfirmacion { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
