//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngresosDocumentos
    {
        public System.Guid IngresoDocumentoId { get; set; }
        public System.Guid ReciboProductoId { get; set; }
        public int ClaveReciboProductoSucursal { get; set; }
        public string NombreArchivo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.Guid> TipoDocumentoDigitalizacionId { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
    
        public virtual ReciboProducto ReciboProducto { get; set; }
        public virtual TipoDocumentoDigitalizacion TipoDocumentoDigitalizacion { get; set; }
    }
}
