//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventarioFisicoEmpleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventarioFisicoEmpleado()
        {
            this.InventarioFisicoControlFoliosBloc = new HashSet<InventarioFisicoControlFoliosBloc>();
            this.InventarioFisicoRutaConteo = new HashSet<InventarioFisicoRutaConteo>();
            this.InventarioFisicoRutaConteo1 = new HashSet<InventarioFisicoRutaConteo>();
            this.InventarioFisicoUsuario = new HashSet<InventarioFisicoUsuario>();
        }
    
        public System.Guid InventarioFisicoEmpleado_Id { get; set; }
        public System.Guid InventarioFisico_Id { get; set; }
        public string ClaveContador { get; set; }
        public Nullable<System.Guid> SucursalAlmacenSeccion_Id { get; set; }
        public int ClaveEmpleado { get; set; }
        public int ClaveFuncion { get; set; }
        public int ClaveEstatus { get; set; }
        public string Grupo { get; set; }
        public string InformacionUsuario { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual InventarioFisico InventarioFisico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventarioFisicoControlFoliosBloc> InventarioFisicoControlFoliosBloc { get; set; }
        public virtual SucursalAlmacenSeccion SucursalAlmacenSeccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventarioFisicoRutaConteo> InventarioFisicoRutaConteo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventarioFisicoRutaConteo> InventarioFisicoRutaConteo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventarioFisicoUsuario> InventarioFisicoUsuario { get; set; }
    }
}
