//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventarioFisicoIdentificadorCorte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventarioFisicoIdentificadorCorte()
        {
            this.InventarioFisicoMarbete = new HashSet<InventarioFisicoMarbete>();
        }
    
        public System.Guid InventarioFisicoIdentificadorCorte_Id { get; set; }
        public System.Guid InventarioFisicoProducto_Id { get; set; }
        public Nullable<System.Guid> IdentificadorCorte_Id { get; set; }
        public Nullable<System.Guid> InventarioUbicacion_Id { get; set; }
        public int ClaveIdentificadorCorte { get; set; }
        public int CantidadVirtual { get; set; }
        public int CantidadSaldo { get; set; }
        public int ExistenciaCierre { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual InventarioFisicoProducto InventarioFisicoProducto { get; set; }
        public virtual ProductoIdentificadorCorte ProductoIdentificadorCorte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventarioFisicoMarbete> InventarioFisicoMarbete { get; set; }
    }
}
