//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventarioFisicoProducto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventarioFisicoProducto()
        {
            this.InventarioFisicoIdentificadorCorte = new HashSet<InventarioFisicoIdentificadorCorte>();
            this.InventarioFisicoMarbete = new HashSet<InventarioFisicoMarbete>();
        }
    
        public System.Guid InventarioFisicoProducto_Id { get; set; }
        public System.Guid InventarioFisico_Id { get; set; }
        public System.Guid SucursalAlmacenSeccion_Id { get; set; }
        public int ClaveArticulo { get; set; }
        public int ClaveMarca { get; set; }
        public string CodigoArticulo { get; set; }
        public string CodigoMarca { get; set; }
        public string GrupoVentaABC { get; set; }
        public string ClaveProductoSegmento3 { get; set; }
        public string DescripcionProducto { get; set; }
        public string CodigoFabrica { get; set; }
        public string CodigoUnidad { get; set; }
        public string Presentacion { get; set; }
        public int ExistenciaOperacion { get; set; }
        public int ExistenciaResguardo { get; set; }
        public int ExistenciaSeccion { get; set; }
        public int ExistenciaCierre { get; set; }
        public Nullable<int> SaldoIdentificador { get; set; }
        public decimal Costo { get; set; }
        public decimal CostoReposicion { get; set; }
        public decimal PromedioRepo { get; set; }
        public int ClaveEstatusProductoInventarioFisico { get; set; }
        public int ClaveEstatus { get; set; }
        public Nullable<int> UsuarioRevision { get; set; }
        public Nullable<System.DateTime> FechaUltimaRevision { get; set; }
        public Nullable<int> UsuarioAuditoria { get; set; }
        public Nullable<System.DateTime> FechaUltimaAuditoria { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        public virtual FabricanteMarcaLinea FabricanteMarcaLinea { get; set; }
        public virtual InventarioFisico InventarioFisico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventarioFisicoIdentificadorCorte> InventarioFisicoIdentificadorCorte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventarioFisicoMarbete> InventarioFisicoMarbete { get; set; }
        public virtual SucursalAlmacenSeccion SucursalAlmacenSeccion { get; set; }
    }
}
