//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventarioFisicoControlFolios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventarioFisicoControlFolios()
        {
            this.InventarioFisicoControlFoliosBloc = new HashSet<InventarioFisicoControlFoliosBloc>();
        }
    
        public System.Guid InventarioFisicoControlFolios_Id { get; set; }
        public System.Guid InventarioFisico_Id { get; set; }
        public System.Guid SucursalAlmacenSeccion_Id { get; set; }
        public int CantidadProductos { get; set; }
        public int CantidadIdentificadoresCorte { get; set; }
        public int FolioInicio { get; set; }
        public int FolioFin { get; set; }
        public int ClaveEstatus { get; set; }
        public decimal PorcentajeProteccion { get; set; }
        public int NumeroCapturistas { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual InventarioFisico InventarioFisico { get; set; }
        public virtual SucursalAlmacenSeccion SucursalAlmacenSeccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventarioFisicoControlFoliosBloc> InventarioFisicoControlFoliosBloc { get; set; }
    }
}
