//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventarioFisicoSeccionConteoCierre
    {
        public System.Guid InventarioFisicoSeccionConteo_Id { get; set; }
        public int Conteo { get; set; }
        public byte[] Archivo { get; set; }
        public Nullable<int> UsuarioAutoriza { get; set; }
        public Nullable<int> UsuarioAutoriza2 { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual InventarioFisicoSeccionConteo InventarioFisicoSeccionConteo { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
