//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventarioFisicoMarbeteRevision
    {
        public System.Guid InventarioFisicoMarbete_Id { get; set; }
        public int ClaveMarbeteConteo { get; set; }
        public int ClaveMarbeteRevision { get; set; }
        public int Cantidad { get; set; }
        public Nullable<int> UsuarioRevision { get; set; }
        public Nullable<System.DateTime> FechaRevision { get; set; }
        public int EmpleadoConteo { get; set; }
        public int EmpleadoCaptura { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Empleado Empleado1 { get; set; }
        public virtual InventarioFisicoMarbeteHistorico InventarioFisicoMarbeteHistorico { get; set; }
    }
}
