//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventarioFisicoSeccionConteo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventarioFisicoSeccionConteo()
        {
            this.InventarioFisicoRutaConteo = new HashSet<InventarioFisicoRutaConteo>();
            this.InventarioFisicoSeccionConteoCierre = new HashSet<InventarioFisicoSeccionConteoCierre>();
        }
    
        public System.Guid InventarioFisicoSeccionConteo_Id { get; set; }
        public System.Guid InventarioFisico_Id { get; set; }
        public System.Guid SucursalAlmacenSeccion_Id { get; set; }
        public int ConteoActual { get; set; }
        public int ConteoSolicitados { get; set; }
        public int ClaveEstatus { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual InventarioFisico InventarioFisico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventarioFisicoRutaConteo> InventarioFisicoRutaConteo { get; set; }
        public virtual SucursalAlmacenSeccion SucursalAlmacenSeccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventarioFisicoSeccionConteoCierre> InventarioFisicoSeccionConteoCierre { get; set; }
    }
}
