//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventarioFisicoImpresion
    {
        public System.Guid InventarioFisicoImpresion_Id { get; set; }
        public System.Guid InventarioFisicoMarbete_Id { get; set; }
        public int Conteo { get; set; }
        public int Pagina { get; set; }
        public int DigitoVerificador { get; set; }
        public int Estatus { get; set; }
        public int ClaveTipoHoja { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public int UsuarioAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<System.Guid> InventarioFisicoEmpleado_Id { get; set; }
    
        public virtual InventarioFisicoMarbete InventarioFisicoMarbete { get; set; }
    }
}
