//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaPreciosFormulaExcel
    {
        public int ClaveListaPreciosFormulaExcel { get; set; }
        public Nullable<int> OpcTipoFormula { get; set; }
        public string Concepto { get; set; }
        public string Columna { get; set; }
        public string Formula { get; set; }
        public short Digitos { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    }
}
