//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientoBanco
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MovimientoBanco()
        {
            this.Divisiones = new HashSet<Divisiones>();
        }
    
        public System.Guid MovimientoBanco_Id { get; set; }
        public System.Guid CuentaBancariaDSA_Id { get; set; }
        public int FolioMovimiento { get; set; }
        public Nullable<int> FolioMovimientoBanco { get; set; }
        public System.DateTime FechaOperacion { get; set; }
        public int ClaveTipoMovimiento { get; set; }
        public int ClaveBeneficiario { get; set; }
        public string DescripcionBanco { get; set; }
        public string ClienteProveedor { get; set; }
        public Nullable<System.Guid> Origen_Id { get; set; }
        public Nullable<int> ClaveOrigen { get; set; }
        public Nullable<System.Guid> MovimientoDestino_Id { get; set; }
        public string ClaveDestino { get; set; }
        public string Referencia { get; set; }
        public Nullable<int> ClaveUsuarioIdentifica { get; set; }
        public int ClaveCategoria { get; set; }
        public decimal Pago { get; set; }
        public decimal Deposito { get; set; }
        public decimal Saldo { get; set; }
        public int Estatus { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<System.DateTime> FechaConciliacion { get; set; }
        public Nullable<int> UsuarioConciliacion { get; set; }
        public Nullable<int> FolioConciliacion { get; set; }
    
        public virtual CuentaBancariaDSA CuentaBancariaDSA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Divisiones> Divisiones { get; set; }
    }
}
