//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientoCuentaxPagar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MovimientoCuentaxPagar()
        {
            this.MovimientoCuentaxPagar1 = new HashSet<MovimientoCuentaxPagar>();
        }
    
        public System.Guid MovimientoCuentaXPagar_Id { get; set; }
        public System.Guid ProveedorAcreedor_Id { get; set; }
        public Nullable<System.Guid> CuentaPorPagar_Id { get; set; }
        public Nullable<System.Guid> PagoCuentaxPagar_Id { get; set; }
        public int FolioMovimiento { get; set; }
        public int ClaveTipoMovimientoCuentaPorPagar { get; set; }
        public Nullable<System.Guid> MovimientoCxPOrigen_Id { get; set; }
        public System.DateTime FechaOperacion { get; set; }
        public int ClaveTipoMoneda { get; set; }
        public decimal FactorCambiario { get; set; }
        public decimal ImporteAjusteCambiario { get; set; }
        public decimal ImporteAnteriorFactura { get; set; }
        public decimal ImporteAnteriorPago { get; set; }
        public decimal ImporteSubTotal { get; set; }
        public Nullable<decimal> PorcentajeIVACalculado { get; set; }
        public decimal ImpuestoAplicado { get; set; }
        public decimal ImporteAplicado { get; set; }
        public decimal SaldoFactura { get; set; }
        public decimal SaldoPago { get; set; }
        public string Referencia { get; set; }
        public string NotaMovimiento { get; set; }
        public string NotaCancelacion { get; set; }
        public int ClaveEstatusCuentaPorPagar { get; set; }
        public int Visible { get; set; }
        public Nullable<System.Guid> SesionUsuario_Id { get; set; }
        public Nullable<int> UsuarioCancela { get; set; }
        public Nullable<System.DateTime> FechaCancela { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public int UsuarioAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual CuentaXPagar CuentaXPagar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovimientoCuentaxPagar> MovimientoCuentaxPagar1 { get; set; }
        public virtual MovimientoCuentaxPagar MovimientoCuentaxPagar2 { get; set; }
        public virtual PagoCuentaxPagar PagoCuentaxPagar { get; set; }
        public virtual ProveedorAcreedor ProveedorAcreedor { get; set; }
        public virtual TipoMoneda TipoMoneda { get; set; }
        public virtual TipoMovimientoCuentaPorPagar TipoMovimientoCuentaPorPagar { get; set; }
    }
}
