//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotaCargo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NotaCargo()
        {
            this.CuentaCobrarCliente = new HashSet<CuentaCobrarCliente>();
            this.NotaCargoImportes = new HashSet<NotaCargoImportes>();
        }
    
        public System.Guid NotaCargo_Id { get; set; }
        public string SerieNotaCargo { get; set; }
        public int FolioNotaCargo { get; set; }
        public int ClaveSucursal { get; set; }
        public short ClaveTipoNotaCargo { get; set; }
        public System.Guid Cliente_Id { get; set; }
        public int ClaveClienteSegmento3 { get; set; }
        public Nullable<System.Guid> SesionCaja_Id { get; set; }
        public Nullable<System.Guid> CargoCliente_Id { get; set; }
        public string ConceptoNotaCargo { get; set; }
        public string DescripcionCliente1 { get; set; }
        public string DescripcionCliente2 { get; set; }
        public int ClaveEstatusNotaCargo { get; set; }
        public Nullable<int> UsuarioCancela { get; set; }
        public Nullable<System.DateTime> FechaCancela { get; set; }
        public string Certificado { get; set; }
        public string AnioAprobacion { get; set; }
        public string NoAprobacion { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<System.Guid> Cheque_Id { get; set; }
    
        public virtual CargoCliente CargoCliente { get; set; }
        public virtual Cheque Cheque { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual ClienteSegmento3 ClienteSegmento3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentaCobrarCliente> CuentaCobrarCliente { get; set; }
        public virtual EstatusNotaCargo EstatusNotaCargo { get; set; }
        public virtual FacturaClienteCFD FacturaClienteCFD { get; set; }
        public virtual SesionCaja SesionCaja { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual TipoNotaCargo TipoNotaCargo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotaCargoImportes> NotaCargoImportes { get; set; }
    }
}
