//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenDespachoEntregaBitacora
    {
        public System.Guid OrdenDespachoId { get; set; }
        public int ClaveOrdenDespacho { get; set; }
        public int ClaveOrdenDespachoSucursal { get; set; }
        public int ClaveSeccion { get; set; }
        public int OpcEstatusOrdenDespachoEntregaBitacora { get; set; }
        public System.DateTime FechaRegistroSeguimiento { get; set; }
        public Nullable<System.DateTime> FechaInicioEntregaSeccion { get; set; }
        public Nullable<System.DateTime> FechaFinEntregaSeccion { get; set; }
        public string ClaveUsuarioAsignadoInicial { get; set; }
        public string ClaveUsuarioAsignadoFinal { get; set; }
        public string ClaveUsuarioRecibeEnrejadoFinal { get; set; }
        public Nullable<System.DateTime> FechaRecibeEnrejado { get; set; }
        public int OpcTipoEntrega { get; set; }
        public string OpcionMesaRuta { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public string Observaciones { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public int CantidadPartidas { get; set; }
        public int CantidadPiezas { get; set; }
    
        public virtual OrdenDespacho OrdenDespacho { get; set; }
        public virtual Seccion Seccion { get; set; }
    }
}
