//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenCompra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenCompra()
        {
            this.OrdenCompraEntrega = new HashSet<OrdenCompraEntrega>();
            this.OrdenCompraImportes = new HashSet<OrdenCompraImportes>();
            this.OrdenCompraProducto = new HashSet<OrdenCompraProducto>();
            this.ReciboProducto = new HashSet<ReciboProducto>();
        }
    
        public int ClaveOrdenCompraSucursal { get; set; }
        public System.Guid OrdenCompraId { get; set; }
        public string SerieOrdenCompra { get; set; }
        public Nullable<int> FolioOrdenCompra { get; set; }
        public int ClaveTipoOrdenCompra { get; set; }
        public int ClaveProveedor { get; set; }
        public int ClaveTipoProveedor { get; set; }
        public int ClaveProveedorSucursal { get; set; }
        public System.Guid ProveedorAcreedor_Id { get; set; }
        public Nullable<int> ClaveTipoCambio { get; set; }
        public Nullable<decimal> ValorTipoCambio { get; set; }
        public string NotaOrdenCompra { get; set; }
        public int ClaveTipoMoneda { get; set; }
        public int ClaveSucursalDestino { get; set; }
        public Nullable<int> ClaveAlmacenDestino { get; set; }
        public Nullable<int> ClaveTipoMonedaOrigen { get; set; }
        public Nullable<int> ClaveTipoMonedaDestino { get; set; }
        public Nullable<int> FactorTipoCambio { get; set; }
        public Nullable<int> DiasPlazoPago { get; set; }
        public int ClaveEstatusOrdenCompra { get; set; }
        public Nullable<int> ClaveProveedorContactoAtencion { get; set; }
        public Nullable<int> ClaveProveedorContactoSucursalAtencion { get; set; }
        public string ContactoTelefono { get; set; }
        public string ContactoCorreo { get; set; }
        public Nullable<int> UsuarioCancela { get; set; }
        public Nullable<System.DateTime> FechaCancela { get; set; }
        public Nullable<int> UsuarioAutoriza { get; set; }
        public Nullable<int> SucursalAutoriza { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public int TipoOrdenCompra { get; set; }
    
        public virtual EstatusOrdenCompra EstatusOrdenCompra { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual TipoCambio TipoCambio { get; set; }
        public virtual TipoMoneda TipoMoneda { get; set; }
        public virtual TipoOrdenCompra TipoOrdenCompra1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenCompraEntrega> OrdenCompraEntrega { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenCompraImportes> OrdenCompraImportes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenCompraProducto> OrdenCompraProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReciboProducto> ReciboProducto { get; set; }
    }
}
