//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenDespachoServicio
    {
        public System.Guid OrdenDespachoId { get; set; }
        public int ClaveOrdenDespachoSucursal { get; set; }
        public int ClaveOrdenDespacho { get; set; }
        public int ClavePartidaServicio { get; set; }
        public System.Guid OrdenDespachoServicio_Id { get; set; }
        public string CodigoServicio { get; set; }
        public string Descripcion { get; set; }
        public string Presentacion { get; set; }
        public decimal FactorTipoCambio { get; set; }
        public int ClaveTipoMonedaDestino { get; set; }
        public string DescripcionCliente1 { get; set; }
        public string DescripcionCliente2 { get; set; }
        public string NotaCancelacion { get; set; }
        public decimal PrecioMN { get; set; }
        public decimal Precio { get; set; }
        public decimal PorcentajeIVA { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public int UsuarioAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual OrdenDespacho OrdenDespacho { get; set; }
    }
}
