//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenDespachoEntrega
    {
        public System.Guid OrdenDespachoId { get; set; }
        public int ClaveOrdenDespacho { get; set; }
        public int ClaveOrdenDespachoSucursal { get; set; }
        public int OpcTipoEntrega { get; set; }
        public int ClaveMesaReparto { get; set; }
        public int OpcEstatusOrdenDespachoEntregaBitacora { get; set; }
        public System.DateTime FechaClienteSolicita { get; set; }
        public Nullable<System.DateTime> FechaEntregaCierra { get; set; }
        public string ClaveUsuarioEntregaMaterial { get; set; }
        public string OpcionMesaRuta { get; set; }
        public System.Guid UsuarioSesion_Id { get; set; }
        public string Observaciones { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual OrdenDespacho OrdenDespacho { get; set; }
    }
}
