//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenEnsamble
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenEnsamble()
        {
            this.OrdenEnsambleDetalle = new HashSet<OrdenEnsambleDetalle>();
        }
    
        public int ClaveOrdenEnsamble { get; set; }
        public int ClaveSucursalOrdenEnsamble { get; set; }
        public int ClaveAlmacen { get; set; }
        public string SerieOrdenEnsamble { get; set; }
        public int FolioOrdenEnsamble { get; set; }
        public int ClaveProductoEnsamble { get; set; }
        public System.Guid Cliente_Id { get; set; }
        public int CantidadEnsamblar { get; set; }
        public decimal CostoIngreso { get; set; }
        public System.DateTime FechaCompromisoEntrega { get; set; }
        public int ClaveEstatusEnsambles { get; set; }
        public int ClaveTipoCambio { get; set; }
        public int ClaveTipoMoneda { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual EstatusEnsambles EstatusEnsambles { get; set; }
        public virtual ProductoEnsamble ProductoEnsamble { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual TipoCambio TipoCambio { get; set; }
        public virtual TipoMoneda TipoMoneda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenEnsambleDetalle> OrdenEnsambleDetalle { get; set; }
    }
}
