//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenDespachoReparto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenDespachoReparto()
        {
            this.ControlFolioRepartoDetalle = new HashSet<ControlFolioRepartoDetalle>();
        }
    
        public System.Guid OrdenDespachoId { get; set; }
        public int ClaveOrdenDespachoReparto { get; set; }
        public int ClaveOrdenDespachoSucursalReparto { get; set; }
        public string NombreLargoContacto { get; set; }
        public string Nombre1Contacto { get; set; }
        public string Nombre2Contacto { get; set; }
        public string ApellidoPaternoContacto { get; set; }
        public string ApellidoMaternoContacto { get; set; }
        public string CorreoElectronico { get; set; }
        public Nullable<int> ClaveTipoTelefono1 { get; set; }
        public string Telefono1 { get; set; }
        public string Extension1 { get; set; }
        public Nullable<short> ClaveTipoTelefono2 { get; set; }
        public string Telefono2 { get; set; }
        public string Extension2 { get; set; }
        public Nullable<short> ClaveTipoTelefono3 { get; set; }
        public string Telefono3 { get; set; }
        public string Extension3 { get; set; }
        public Nullable<System.DateTime> HoraInicial { get; set; }
        public Nullable<System.DateTime> HoraFinal { get; set; }
        public string HASHDireccion { get; set; }
        public Nullable<int> ClaveTipoRutaReparto { get; set; }
        public Nullable<int> ClaveEstatusEntrega { get; set; }
        public short ClaveTipoVialidad { get; set; }
        public Nullable<int> ClaveTipoDireccion { get; set; }
        public Nullable<int> ClaveColonia { get; set; }
        public string Calle { get; set; }
        public string NumeroExterno { get; set; }
        public string NumeroInterno { get; set; }
        public string Colonia { get; set; }
        public string CodigoPostal { get; set; }
        public string EntreCalles { get; set; }
        public string Observacion { get; set; }
        public string Recibe { get; set; }
        public string DireccionAnterior { get; set; }
        public bool Activo { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<int> ClaveTipoPaquetería { get; set; }
        public decimal PesoBrutoProducto { get; set; }
        public Nullable<System.Guid> ProveedorPaqueteria_Id { get; set; }
    
        public virtual Colonia Colonia1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlFolioRepartoDetalle> ControlFolioRepartoDetalle { get; set; }
        public virtual EstatusEntrega EstatusEntrega { get; set; }
        public virtual OrdenDespacho OrdenDespacho { get; set; }
        public virtual TipoDireccion TipoDireccion { get; set; }
        public virtual TipoRutaReparto TipoRutaReparto { get; set; }
        public virtual TipoTelefono TipoTelefono { get; set; }
        public virtual TipoVialidad TipoVialidad { get; set; }
    }
}
