//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenDespachoProducto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenDespachoProducto()
        {
            this.OrdenCorte = new HashSet<OrdenCorte>();
        }
    
        public System.Guid OrdenDespachoProductoId { get; set; }
        public System.Guid OrdenDespachoId { get; set; }
        public int ClaveOrdenDespachoSucursal { get; set; }
        public int ClaveOrdenDespacho { get; set; }
        public int ClaveOrdenDespachoPartida { get; set; }
        public System.Guid OrdenDespachoPartida_Id { get; set; }
        public int ClaveArticulo { get; set; }
        public int ClaveMarcaLinea { get; set; }
        public Nullable<int> ClaveAlmacenSucursal { get; set; }
        public Nullable<System.Guid> SeccionProductoID { get; set; }
        public Nullable<decimal> CostoSalida { get; set; }
        public Nullable<int> NumeroPartidaCliente { get; set; }
        public int CantidadExistencia { get; set; }
        public int CantidadSolicitada { get; set; }
        public int CantidadSolicitadaResguardo { get; set; }
        public int CantidadDevuelta { get; set; }
        public string GrupoVentaABC { get; set; }
        public string CodigoProductoSegmento3 { get; set; }
        public string DescripcionProducto { get; set; }
        public string CodigoFabrica { get; set; }
        public string CodigoUnidad { get; set; }
        public string Presentacion { get; set; }
        public decimal PrecioLista { get; set; }
        public decimal PrecioCreditoOrigen { get; set; }
        public decimal PrecioVenta { get; set; }
        public decimal PrecioVentaUnitario { get; set; }
        public int ClaveTipoMonedaOrigen { get; set; }
        public int ClaveTipoMonedaDestino { get; set; }
        public decimal FactorTipoCambio { get; set; }
        public int ExistenciaMinima { get; set; }
        public int ExistenciaMaxima { get; set; }
        public string Nota { get; set; }
        public string DescripcionCliente1 { get; set; }
        public string DescripcionCliente2 { get; set; }
        public string NotaCancelacion { get; set; }
        public int OpcEstatusDespachoProducto { get; set; }
        public Nullable<int> UsuarioCambio { get; set; }
        public Nullable<System.DateTime> FechaCambio { get; set; }
        public Nullable<int> ClaveTipoDocumentoOrigen { get; set; }
        public Nullable<System.Guid> DocumentoOrigen_Id { get; set; }
        public Nullable<int> ClaveSucursalDocumentoOrigen { get; set; }
        public Nullable<int> ClaveDocumentoOrigen { get; set; }
        public Nullable<int> NumeroPartidaOrigen { get; set; }
        public Nullable<int> ClaveAlmacen { get; set; }
        public Nullable<System.Guid> ProductoPromocion_Id { get; set; }
        public Nullable<int> PartidaPromocion { get; set; }
        public bool AceptaDevolucion { get; set; }
        public bool ExisteFactura { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public int UsuarioAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public decimal PesoUnitario { get; set; }
        public string CodigoPromocion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenCorte> OrdenCorte { get; set; }
        public virtual OrdenDespacho OrdenDespacho { get; set; }
        public virtual OrdenDespachoProductoImporte OrdenDespachoProductoImporte { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual ProductoPromocionDetalle ProductoPromocionDetalle { get; set; }
        public virtual SeccionProducto SeccionProducto { get; set; }
    }
}
