//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenCompraProductoSobrestock
    {
        public System.Guid OrdenCompraProductoSobrestockId { get; set; }
        public System.Guid OrdenCompraProductoId { get; set; }
        public int CantidadPactadaInicial { get; set; }
        public int CantidadPactadaActual { get; set; }
        public int CantidadSurtida { get; set; }
        public int CantidadCancelada { get; set; }
        public int CantidadSaldo { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public int UsuarioAutoriza { get; set; }
        public System.DateTime FechaAutoriza { get; set; }
    
        public virtual OrdenCompraProducto OrdenCompraProducto { get; set; }
    }
}
