//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagoCuentaxPagar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PagoCuentaxPagar()
        {
            this.MovimientoCuentaxPagar = new HashSet<MovimientoCuentaxPagar>();
        }
    
        public System.Guid PagoCuentaxPagar_Id { get; set; }
        public int FolioPagoCuentaXPagar { get; set; }
        public System.Guid ProveedorAcreedor_Id { get; set; }
        public int ClaveSucursal { get; set; }
        public int ClaveTipoFormaPago { get; set; }
        public string Referencia { get; set; }
        public System.DateTime FechaAplicacion { get; set; }
        public int ClaveTipoMoneda { get; set; }
        public decimal FactorCambiarioOrigen { get; set; }
        public decimal FactorCambiarioActualizado { get; set; }
        public Nullable<System.DateTime> FechaTipoCambioActualizado { get; set; }
        public Nullable<System.Guid> Origen_Id { get; set; }
        public Nullable<int> ClaveOrigen { get; set; }
        public decimal ImporteTotal { get; set; }
        public decimal ImporteAplicado { get; set; }
        public decimal ImporteTotalMx { get; set; }
        public decimal Saldo { get; set; }
        public decimal ImporteAjusteCambiario { get; set; }
        public int ClaveEstatusCuentaPorPagar { get; set; }
        public Nullable<System.Guid> ProcesoPagoPaquete_Id { get; set; }
        public Nullable<int> UsuarioCancela { get; set; }
        public Nullable<System.DateTime> FechaCancela { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovimientoCuentaxPagar> MovimientoCuentaxPagar { get; set; }
        public virtual ProcesoPagoCxPPaquete ProcesoPagoCxPPaquete { get; set; }
        public virtual ProveedorAcreedor ProveedorAcreedor { get; set; }
        public virtual TipoFormaPagoCxP TipoFormaPagoCxP { get; set; }
    }
}
