//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagoCobranza
    {
        public System.Guid PagoCobranza_Id { get; set; }
        public Nullable<System.Guid> PagoCliente_Id { get; set; }
        public System.Guid CobranzaCliente_Id { get; set; }
        public System.Guid Cliente_Id { get; set; }
        public int ClaveSucursal { get; set; }
        public short ClaveTipoFormaPago { get; set; }
        public int ClaveTipoMoneda { get; set; }
        public int ClaveTipoCambio { get; set; }
        public decimal ValorTipoCambio { get; set; }
        public decimal ImportePago { get; set; }
        public Nullable<int> ClaveBanco { get; set; }
        public string NumeroCuenta { get; set; }
        public string Documento { get; set; }
        public Nullable<System.DateTime> FechaCheque { get; set; }
        public string Observaciones { get; set; }
        public int ClaveTipoMovimientoCuentaPorCobrar { get; set; }
        public int EstatusPagoCobranza { get; set; }
        public System.Guid UsuarioSesion_Id { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual Banco Banco { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual CobranzaCliente CobranzaCliente { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual TipoCambio TipoCambio { get; set; }
        public virtual TipoFormaPago TipoFormaPago { get; set; }
        public virtual TipoMoneda TipoMoneda { get; set; }
        public virtual TipoMovimientoCuentaPorCobrar TipoMovimientoCuentaPorCobrar { get; set; }
    }
}
