//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoClienteProducto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PedidoClienteProducto()
        {
            this.PedidoClienteProductoImportes = new HashSet<PedidoClienteProductoImportes>();
        }
    
        public int ClavePedidoClientePartida { get; set; }
        public int ClavePedidoCliente { get; set; }
        public int ClavePedidoClienteSucursal { get; set; }
        public System.Guid PedidoClientePartida_Id { get; set; }
        public int ClaveArticulo { get; set; }
        public int ClaveMarcaLinea { get; set; }
        public Nullable<int> ClaveAlmacenSucursal { get; set; }
        public Nullable<int> ClaveAlmacen { get; set; }
        public string GrupoVentaABC { get; set; }
        public string DescripcionProducto { get; set; }
        public string CodigoFabrica { get; set; }
        public string CodigoUnidad { get; set; }
        public string Presentacion { get; set; }
        public int CantidadPactadaInicial { get; set; }
        public int CantidadPactadaActual { get; set; }
        public int CantidadExcedente { get; set; }
        public int CantidadSurtida { get; set; }
        public int CantidadSaldo { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public decimal PrecioLista { get; set; }
        public decimal PrecioCreditoOrigen { get; set; }
        public Nullable<decimal> PrecioVenta { get; set; }
        public Nullable<decimal> PrecioPromocion { get; set; }
        public decimal PrecioPactado { get; set; }
        public int ClaveTipoMonedaOrigen { get; set; }
        public int ClaveTipoMonedaDestino { get; set; }
        public decimal FactorTipoCambio { get; set; }
        public string DescripcionCliente1 { get; set; }
        public string DescripcionCliente2 { get; set; }
        public Nullable<int> UsuarioCancela { get; set; }
        public Nullable<System.DateTime> FechaCancela { get; set; }
        public Nullable<int> UsuarioAutoriza { get; set; }
        public Nullable<System.DateTime> FechaAutoriza { get; set; }
        public Nullable<int> UsuarioExcedente { get; set; }
        public Nullable<System.DateTime> FechaExcedente { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual PedidoCliente PedidoCliente { get; set; }
        public virtual Producto Producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoClienteProductoImportes> PedidoClienteProductoImportes { get; set; }
    }
}
