//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoCliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PedidoCliente()
        {
            this.OrdenDespacho = new HashSet<OrdenDespacho>();
            this.PedidoClienteImportes = new HashSet<PedidoClienteImportes>();
            this.PedidoClienteProducto = new HashSet<PedidoClienteProducto>();
        }
    
        public int ClavePedidoCliente { get; set; }
        public int ClavePedidoClienteSucursal { get; set; }
        public System.Guid PedidoCliente_Id { get; set; }
        public string SeriePedido { get; set; }
        public int FolioPedido { get; set; }
        public System.Guid Cliente_Id { get; set; }
        public string PO { get; set; }
        public int ClaveTipoPedido { get; set; }
        public string RFC { get; set; }
        public string NombreLargo { get; set; }
        public string Colonia { get; set; }
        public string Estado { get; set; }
        public string Municipio { get; set; }
        public string Pais { get; set; }
        public string Direccion { get; set; }
        public string CodigoPostal { get; set; }
        public int ClaveTipoMoneda { get; set; }
        public Nullable<int> ClaveTipoCambio { get; set; }
        public Nullable<decimal> FactorTipoCambio { get; set; }
        public Nullable<System.Guid> AnticipoCliente_Id { get; set; }
        public Nullable<decimal> PorcentajeAnticipo { get; set; }
        public Nullable<int> ClaveReferenciaNivel1 { get; set; }
        public Nullable<int> ClaveReferenciaNivel2 { get; set; }
        public Nullable<bool> Especial { get; set; }
        public string NotaPedidoCliente { get; set; }
        public int ClaveEstatusPedidoCliente { get; set; }
        public Nullable<int> UsuarioCancela { get; set; }
        public Nullable<System.DateTime> FechaCancela { get; set; }
        public Nullable<int> UsuarioAutoriza { get; set; }
        public Nullable<System.DateTime> FechaAutoriza { get; set; }
        public Nullable<int> SucursalAutoriza { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual AnticipoCliente AnticipoCliente { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual EstatusPedidoCliente EstatusPedidoCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenDespacho> OrdenDespacho { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual TipoCambio TipoCambio { get; set; }
        public virtual TipoMoneda TipoMoneda { get; set; }
        public virtual TipoPedido TipoPedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoClienteImportes> PedidoClienteImportes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoClienteProducto> PedidoClienteProducto { get; set; }
    }
}
