//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoInternoProducto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PedidoInternoProducto()
        {
            this.OrdenCompraProducto = new HashSet<OrdenCompraProducto>();
            this.PedidoInternoProductoImportes = new HashSet<PedidoInternoProductoImportes>();
        }
    
        public string SeriePedidoInterno { get; set; }
        public int FolioPedidoInterno { get; set; }
        public int ClavePedidoInternoPartida { get; set; }
        public System.Guid PedidoInternoProducto_Id { get; set; }
        public string SerieDocumentoOrigen { get; set; }
        public Nullable<int> FolioDocumentoOrigen { get; set; }
        public Nullable<int> PartidaDocumentoOrigen { get; set; }
        public int ClaveArticulo { get; set; }
        public int ClaveMarcaLinea { get; set; }
        public int ClaveEstatusPedidoInterno { get; set; }
        public Nullable<int> UsuarioPromesaEntrega { get; set; }
        public Nullable<System.DateTime> FechaPromesaEntrega { get; set; }
        public Nullable<int> ClaveAlmacenSucursal { get; set; }
        public int CantidadExistencia { get; set; }
        public int CantidadSolicitada { get; set; }
        public string GrupoVentaABC { get; set; }
        public decimal PrecioLista { get; set; }
        public decimal PrecioVenta { get; set; }
        public Nullable<int> ClaveTipoMonedaOrigen { get; set; }
        public Nullable<int> ClaveTipoMonedaDestino { get; set; }
        public Nullable<decimal> FactorTipoCambio { get; set; }
        public int ExistenciaMinima { get; set; }
        public int ExistenciaMaxima { get; set; }
        public string DescripcionCliente1 { get; set; }
        public string DescripcionCliente2 { get; set; }
        public Nullable<int> UsuarioCancela { get; set; }
        public Nullable<System.DateTime> FechaCancela { get; set; }
        public Nullable<int> ClaveTipoDocumentoOrigen { get; set; }
        public Nullable<System.Guid> DocumentoOrigen_Id { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual EstatusPedidoInterno EstatusPedidoInterno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenCompraProducto> OrdenCompraProducto { get; set; }
        public virtual PedidoInterno PedidoInterno { get; set; }
        public virtual Producto Producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoInternoProductoImportes> PedidoInternoProductoImportes { get; set; }
    }
}
