//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoDescuento
    {
        public int ClaveProductoDescuento { get; set; }
        public int ClaveArticulo { get; set; }
        public int ClaveMarcaLinea { get; set; }
        public int ClaveTipoDescuentoProducto { get; set; }
        public decimal Monto { get; set; }
        public int Dias { get; set; }
        public Nullable<System.DateTime> FechaInicioDescuento { get; set; }
        public Nullable<System.DateTime> FechaFinDescuento { get; set; }
        public bool Activo { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual TipoDescuentoProducto TipoDescuentoProducto { get; set; }
    }
}
