//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoPromocionCodigo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductoPromocionCodigo()
        {
            this.ProductoPromocionCodigoAplicacion = new HashSet<ProductoPromocionCodigoAplicacion>();
        }
    
        public System.Guid ProductoPromocionCodigo_Id { get; set; }
        public System.Guid ProductoPromocion_Id { get; set; }
        public string CodigoPromocion { get; set; }
        public int Estatus { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public bool Impreso { get; set; }
    
        public virtual ProductoPromocion ProductoPromocion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductoPromocionCodigoAplicacion> ProductoPromocionCodigoAplicacion { get; set; }
    }
}
