//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoPromocionDetalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductoPromocionDetalle()
        {
            this.CotizacionClienteProducto = new HashSet<CotizacionClienteProducto>();
            this.OrdenDespachoProducto = new HashSet<OrdenDespachoProducto>();
        }
    
        public System.Guid ProductoPromocion_Id { get; set; }
        public int PartidaPromocion { get; set; }
        public System.Guid SucursalProducto_Id { get; set; }
        public decimal DescuentoPromocion { get; set; }
        public Nullable<int> VentaMinima { get; set; }
        public Nullable<int> VentaMaxima { get; set; }
        public Nullable<int> CantidadPromocion { get; set; }
        public int Saldo { get; set; }
        public string PID { get; set; }
        public int AplicaDescuentoOperacion { get; set; }
        public int DisponibleParaPromesaCompra { get; set; }
        public string NotaVenta { get; set; }
        public int AceptaDevolucion { get; set; }
        public bool Activo { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CotizacionClienteProducto> CotizacionClienteProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenDespachoProducto> OrdenDespachoProducto { get; set; }
        public virtual ProductoPromocion ProductoPromocion { get; set; }
        public virtual SucursalProducto SucursalProducto { get; set; }
    }
}
