//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoIdentificadorCorte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductoIdentificadorCorte()
        {
            this.BitacoraIdentificadorCorte = new HashSet<BitacoraIdentificadorCorte>();
            this.InventarioFisicoIdentificadorCorte = new HashSet<InventarioFisicoIdentificadorCorte>();
            this.OrdenCorte = new HashSet<OrdenCorte>();
            this.ValeInterAlmacenProducto = new HashSet<ValeInterAlmacenProducto>();
        }
    
        public System.Guid IdentificadorCorte_ID { get; set; }
        public System.Guid SeccionProductoID { get; set; }
        public Nullable<System.Guid> KardexID { get; set; }
        public Nullable<System.Guid> InventarioUbicacion_Id { get; set; }
        public int FolioBitacoraIdentificadorCorte { get; set; }
        public int ClaveIdentificadorCorte { get; set; }
        public int ClaveTipoMovimientoInventario { get; set; }
        public int CantidadInicial { get; set; }
        public int CantidadVirtual { get; set; }
        public int CantidadSaldo { get; set; }
        public Nullable<int> OpcEstatusIdentificadorCorte { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BitacoraIdentificadorCorte> BitacoraIdentificadorCorte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventarioFisicoIdentificadorCorte> InventarioFisicoIdentificadorCorte { get; set; }
        public virtual InventarioUbicacion InventarioUbicacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenCorte> OrdenCorte { get; set; }
        public virtual SeccionProducto SeccionProducto { get; set; }
        public virtual TipoMovimientoInventario TipoMovimientoInventario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ValeInterAlmacenProducto> ValeInterAlmacenProducto { get; set; }
    }
}
