//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoCambioUnidadDestino
    {
        public int ClaveProductoCambioUnidadDestino { get; set; }
        public int ClaveCambio { get; set; }
        public int ClaveArticulo { get; set; }
        public int ClaveMarcaLinea { get; set; }
        public Nullable<System.Guid> UnidadPresentacionOrigen_Id { get; set; }
        public Nullable<System.Guid> UnidadPresentacionDestino_Id { get; set; }
        public short ClaveUnidadMedidaOrigen { get; set; }
        public short ClaveUnidadMedidaDestino { get; set; }
        public int CantidadOrigen { get; set; }
        public int CantidadDestino { get; set; }
        public int Cantidad { get; set; }
        public bool Activo { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual ProductoCambioUnidadOrigen ProductoCambioUnidadOrigen { get; set; }
    }
}
