//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.ClienteDescripcionDetalle = new HashSet<ClienteDescripcionDetalle>();
            this.CotizacionClienteProducto = new HashSet<CotizacionClienteProducto>();
            this.CotizacionClienteProductoHojaTrabajo = new HashSet<CotizacionClienteProductoHojaTrabajo>();
            this.Kardex = new HashSet<Kardex>();
            this.OrdenCompraProducto = new HashSet<OrdenCompraProducto>();
            this.OrdenDespachoProducto = new HashSet<OrdenDespachoProducto>();
            this.PedidoClienteProducto = new HashSet<PedidoClienteProducto>();
            this.PedidoInternoProducto = new HashSet<PedidoInternoProducto>();
            this.ProductoCambioUnidadDestino = new HashSet<ProductoCambioUnidadDestino>();
            this.ProductoCambioUnidadOrigen = new HashSet<ProductoCambioUnidadOrigen>();
            this.ProductoDescuento = new HashSet<ProductoDescuento>();
            this.ProductoEnsamble = new HashSet<ProductoEnsamble>();
            this.ProductoEnsambleDetalle = new HashSet<ProductoEnsambleDetalle>();
            this.ProductoFactor = new HashSet<ProductoFactor>();
            this.ProductoNegadoCatalogo = new HashSet<ProductoNegadoCatalogo>();
            this.ProductoPrecioHistorico = new HashSet<ProductoPrecioHistorico>();
            this.ReciboProductoDetalle = new HashSet<ReciboProductoDetalle>();
            this.SinonimoProducto = new HashSet<SinonimoProducto>();
            this.SucursalProducto = new HashSet<SucursalProducto>();
            this.ValeInterAlmacenProducto = new HashSet<ValeInterAlmacenProducto>();
        }
    
        public int ClaveArticulo { get; set; }
        public int ClaveMarcaLinea { get; set; }
        public string ClaveProducto { get; set; }
        public System.Guid Producto_Id { get; set; }
        public Nullable<System.Guid> ProductoRemplazo_Id { get; set; }
        public string CodigoFabrica { get; set; }
        public string CodigoProveedor { get; set; }
        public decimal PrecioDeLista { get; set; }
        public decimal Factor { get; set; }
        public decimal PrecioPublico { get; set; }
        public Nullable<decimal> PrecioCompra { get; set; }
        public decimal IVA { get; set; }
        public Nullable<int> Paquete { get; set; }
        public Nullable<int> SubPaquete { get; set; }
        public int ClaveTipoMonedaOrigen { get; set; }
        public int ClaveTipoMonedaDestino { get; set; }
        public Nullable<System.DateTime> FechaTipoCambio { get; set; }
        public Nullable<decimal> FactorTipoCambio { get; set; }
        public short ClaveTipoProducto { get; set; }
        public string ClaveProductoSegmento3 { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public Nullable<decimal> Ancho { get; set; }
        public Nullable<decimal> Alto { get; set; }
        public Nullable<decimal> Diametro { get; set; }
        public Nullable<decimal> Espesor { get; set; }
        public Nullable<decimal> Volumen { get; set; }
        public decimal Longitud { get; set; }
        public decimal VentaDiariaPromedio { get; set; }
        public decimal VentaPromedioFactura { get; set; }
        public Nullable<bool> Activo { get; set; }
        public int EsTrameria { get; set; }
        public int EstatusProducto { get; set; }
        public string ClaveProductoSegmento1 { get; set; }
        public string ClaveProductoSegmento2 { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public string ABC1 { get; set; }
        public string ABC2 { get; set; }
        public string ABC3 { get; set; }
        public Nullable<System.DateTime> FechaBajaLogica { get; set; }
        public string NombreProducto { get; set; }
        public string DescripcionProducto { get; set; }
        public string DescripcionProveedor { get; set; }
        public int Flags { get; set; }
        public string Metadatos { get; set; }
        public Nullable<bool> EsFragil { get; set; }
        public Nullable<bool> HabilitarEnvio { get; set; }
        public Nullable<bool> EnvioGratuito { get; set; }
        public Nullable<bool> Publicado { get; set; }
        public string ClaveProdServ { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClienteDescripcionDetalle> ClienteDescripcionDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CotizacionClienteProducto> CotizacionClienteProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CotizacionClienteProductoHojaTrabajo> CotizacionClienteProductoHojaTrabajo { get; set; }
        public virtual FabricanteMarcaLinea FabricanteMarcaLinea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kardex> Kardex { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenCompraProducto> OrdenCompraProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenDespachoProducto> OrdenDespachoProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoClienteProducto> PedidoClienteProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoInternoProducto> PedidoInternoProducto { get; set; }
        public virtual ProductoSegmento3 ProductoSegmento3 { get; set; }
        public virtual TipoMoneda TipoMoneda { get; set; }
        public virtual TipoMoneda TipoMoneda1 { get; set; }
        public virtual TipoProducto TipoProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductoCambioUnidadDestino> ProductoCambioUnidadDestino { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductoCambioUnidadOrigen> ProductoCambioUnidadOrigen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductoDescuento> ProductoDescuento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductoEnsamble> ProductoEnsamble { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductoEnsambleDetalle> ProductoEnsambleDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductoFactor> ProductoFactor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductoNegadoCatalogo> ProductoNegadoCatalogo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductoPrecioHistorico> ProductoPrecioHistorico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReciboProductoDetalle> ReciboProductoDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SinonimoProducto> SinonimoProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SucursalProducto> SucursalProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ValeInterAlmacenProducto> ValeInterAlmacenProducto { get; set; }
    }
}
