//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoPrecioHistorico
    {
        public int ClaveArticulo { get; set; }
        public int ClaveMarcaLinea { get; set; }
        public System.DateTime FechaAplicacion { get; set; }
        public Nullable<System.Guid> PrecioAvisoCambio_Id { get; set; }
        public int ClaveTipoMoneda { get; set; }
        public decimal PrecioLista { get; set; }
        public decimal FactorTipoCambio { get; set; }
        public decimal PrecioListaDSA { get; set; }
        public decimal DC1 { get; set; }
        public decimal DC2 { get; set; }
        public decimal DC3 { get; set; }
        public decimal DC4 { get; set; }
        public decimal DC5 { get; set; }
        public decimal DC6 { get; set; }
        public decimal DC7 { get; set; }
        public decimal DF1 { get; set; }
        public Nullable<decimal> FactorCompra { get; set; }
        public Nullable<decimal> DescuentoCompra { get; set; }
        public Nullable<decimal> CostoRepoFinc { get; set; }
        public decimal Bonificacion { get; set; }
        public Nullable<decimal> CostoRepoFinBonificacion { get; set; }
        public decimal CargoDSAComp { get; set; }
        public decimal CargoDSAFinc { get; set; }
        public decimal CargoDSAAjuste { get; set; }
        public decimal DescuentoDSAAjuste { get; set; }
        public Nullable<decimal> FactorPrecio { get; set; }
        public decimal PrecioCreditoDSA { get; set; }
        public decimal PrecioContadoDSA { get; set; }
        public Nullable<decimal> UtilidadPrecioContado { get; set; }
        public Nullable<decimal> MargenPrecioContado { get; set; }
        public Nullable<decimal> MargenPrecioContadoBonificacion { get; set; }
        public Nullable<decimal> DescuentoPrecioCreditoDSA { get; set; }
        public Nullable<decimal> DescuentoPrecioContadoDSA { get; set; }
        public Nullable<decimal> CompetdorPrecioContado { get; set; }
        public Nullable<decimal> CompetidorDiferencia { get; set; }
        public decimal CostoPromedio { get; set; }
        public Nullable<decimal> CostoRepoFincVsPromedio { get; set; }
        public int Cantidad { get; set; }
        public Nullable<decimal> EnDias { get; set; }
        public Nullable<decimal> MargenCostoRepoFinc { get; set; }
        public Nullable<decimal> MargenCostoPromedio { get; set; }
        public Nullable<decimal> VentaPromedio { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
    
        public virtual PrecioAvisoCambio PrecioAvisoCambio { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual TipoMoneda TipoMoneda { get; set; }
    }
}
