//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProveedorAcreedorBanco
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProveedorAcreedorBanco()
        {
            this.ProcesoPagoCxPDetalle = new HashSet<ProcesoPagoCxPDetalle>();
        }
    
        public System.Guid ProveedorAcreedor_Id { get; set; }
        public int ClaveProveedorAcreedorBanco { get; set; }
        public int ClaveBanco { get; set; }
        public string SucursalCuenta { get; set; }
        public string Cuenta { get; set; }
        public string CLABE { get; set; }
        public string Convenio { get; set; }
        public string ReferenciaCIE { get; set; }
        public int ClaveTipoMoneda { get; set; }
        public string Observaciones { get; set; }
        public int AplicaCrediproveedor { get; set; }
        public int DiasCrediproveedor { get; set; }
        public int Estatus { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual Banco Banco { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcesoPagoCxPDetalle> ProcesoPagoCxPDetalle { get; set; }
        public virtual ProveedorAcreedor ProveedorAcreedor { get; set; }
        public virtual TipoMoneda TipoMoneda { get; set; }
    }
}
