//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        public int ClaveProveedor { get; set; }
        public int ClaveProveedorSucursal { get; set; }
        public int ClaveTipoProveedor { get; set; }
        public System.Guid ProveedorAcreedor_Id { get; set; }
        public Nullable<short> OpcProveedorTipoFiscal { get; set; }
        public string LiteralesRFC { get; set; }
        public string NumeralesRFC { get; set; }
        public string HomoclaveRFC { get; set; }
        public string RFC { get; set; }
        public string NombreLargo { get; set; }
        public string RazonSocial { get; set; }
        public string Nombre_1 { get; set; }
        public string Nombre_2 { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public bool Activo { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual Sucursal Sucursal { get; set; }
        public virtual TipoProveedor TipoProveedor { get; set; }
    }
}
