//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReciboProductoDetalle
    {
        public int ClaveReciboProductoPartida { get; set; }
        public int ClaveArticulo { get; set; }
        public int ClaveMarcaLinea { get; set; }
        public string GrupoVentaABC { get; set; }
        public string DescripcionProducto { get; set; }
        public string CodigoFabrica { get; set; }
        public string CodigoUnidad { get; set; }
        public string Presentacion { get; set; }
        public Nullable<int> ClaveExcedenteSucursal { get; set; }
        public Nullable<int> ClaveExcedente { get; set; }
        public int ClavePartidaOrigen { get; set; }
        public Nullable<int> ClaveDocumentoOrigen { get; set; }
        public Nullable<int> ClaveDocumentoOrigenSucursal { get; set; }
        public Nullable<int> ClaveAlmacenRecibe { get; set; }
        public Nullable<int> ClaveAlmacenRecibeSucursal { get; set; }
        public int CantidadRecibida { get; set; }
        public int CantidadRechazada { get; set; }
        public Nullable<int> OpcCausaRechazo { get; set; }
        public Nullable<int> OpcValidacionCosto { get; set; }
        public Nullable<bool> ErrorValidacionCosto { get; set; }
        public decimal PrecioLista { get; set; }
        public decimal CostoUnitario { get; set; }
        public int CantidadFacturada { get; set; }
        public decimal PrecioFactura { get; set; }
        public decimal CostoUnitarioFactura { get; set; }
        public Nullable<int> ClaveTipoMonedaOrigen { get; set; }
        public Nullable<int> ClaveTipoMonedaDestino { get; set; }
        public Nullable<decimal> FactorTipoCambio { get; set; }
        public Nullable<System.DateTime> FechaProgramadaRecepcion { get; set; }
        public decimal DescuentoComercial1 { get; set; }
        public decimal DescuentoComercial2 { get; set; }
        public decimal DescuentoComercial3 { get; set; }
        public decimal DescuentoComercial4 { get; set; }
        public decimal DescuentoComercial5 { get; set; }
        public decimal DescuentoComercial6 { get; set; }
        public decimal DescuentoComercial7 { get; set; }
        public decimal DescuentoFinanciero1 { get; set; }
        public decimal DescuentoFinanciero2 { get; set; }
        public Nullable<System.Guid> Kardex_Id { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public System.Guid ReciboProductoDetalleId { get; set; }
        public System.Guid ReciboProductoId { get; set; }
        public Nullable<System.Guid> OrdenCompraProductoExcedenteId { get; set; }
    
        public virtual OrdenCompraProductoExcedente OrdenCompraProductoExcedente { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual ReciboProducto ReciboProducto { get; set; }
    }
}
