//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferenciaBancariaTipoDocumento
    {
        public int ClaveTipoDocumento { get; set; }
        public int ClaveBanco { get; set; }
        public int ClaveCuenta { get; set; }
        public int ClaveSucursal { get; set; }
        public int ClaveTipoMoneda { get; set; }
        public string Cuenta { get; set; }
        public string SucursalBancaria { get; set; }
        public string CLABE { get; set; }
        public bool Activo { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual Banco Banco { get; set; }
        public virtual TipoDocumento TipoDocumento { get; set; }
        public virtual TipoMoneda TipoMoneda { get; set; }
    }
}
