//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeccionProductoUbicacion
    {
        public System.Guid SeccionProducto_Id { get; set; }
        public System.Guid InventarioUbicacion_Id { get; set; }
        public int Capacidad { get; set; }
        public int ClaveTipoUbicacion { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public decimal Frente { get; set; }
        public decimal Fondo { get; set; }
        public decimal Altura { get; set; }
    
        public virtual InventarioUbicacion InventarioUbicacion { get; set; }
        public virtual SeccionProducto SeccionProducto { get; set; }
        public virtual TipoUbicacion TipoUbicacion { get; set; }
    }
}
