//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeccionProducto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SeccionProducto()
        {
            this.DevolucionClienteProducto = new HashSet<DevolucionClienteProducto>();
            this.OrdenDespachoProducto = new HashSet<OrdenDespachoProducto>();
            this.ProductoIdentificadorCorte = new HashSet<ProductoIdentificadorCorte>();
            this.SeccionProductoBitacora = new HashSet<SeccionProductoBitacora>();
            this.SeccionProductoUbicacion = new HashSet<SeccionProductoUbicacion>();
        }
    
        public System.Guid SeccionProductoID { get; set; }
        public System.Guid AlmacenProductoId { get; set; }
        public Nullable<System.Guid> SucursalAlmacenSeccion_Id { get; set; }
        public int ClaveSeccion { get; set; }
        public int ExistenciaMaxima { get; set; }
        public int ExistenciaMinima { get; set; }
        public int ExistenciaProducto { get; set; }
        public int ExistenciaSeccion { get; set; }
        public int ExistenciaExcedente { get; set; }
        public int FolioRegistroBitacora { get; set; }
        public bool Activo { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual AlmacenProducto AlmacenProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DevolucionClienteProducto> DevolucionClienteProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenDespachoProducto> OrdenDespachoProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductoIdentificadorCorte> ProductoIdentificadorCorte { get; set; }
        public virtual Seccion Seccion { get; set; }
        public virtual SucursalAlmacenSeccion SucursalAlmacenSeccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeccionProductoBitacora> SeccionProductoBitacora { get; set; }
        public virtual SeccionProductoCosto SeccionProductoCosto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeccionProductoUbicacion> SeccionProductoUbicacion { get; set; }
    }
}
