//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SesionCaja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SesionCaja()
        {
            this.CuentaCobrarCliente = new HashSet<CuentaCobrarCliente>();
            this.CuentaCobrarClienteMovimiento = new HashSet<CuentaCobrarClienteMovimiento>();
            this.EfectivoEnResguardo = new HashSet<EfectivoEnResguardo>();
            this.EntregaEfectivo = new HashSet<EntregaEfectivo>();
            this.FacturaCliente = new HashSet<FacturaCliente>();
            this.NotaCargo = new HashSet<NotaCargo>();
            this.NotaCredito = new HashSet<NotaCredito>();
            this.PagoCliente = new HashSet<PagoCliente>();
            this.SesionCajaCierre = new HashSet<SesionCajaCierre>();
            this.SesionFacturaEntrega = new HashSet<SesionFacturaEntrega>();
        }
    
        public System.Guid SesionCaja_Id { get; set; }
        public string SerieSesion { get; set; }
        public int FolioSesion { get; set; }
        public int ClaveSucursal { get; set; }
        public int ClaveUsuario { get; set; }
        public decimal Dotacion { get; set; }
        public Nullable<System.DateTime> FechaSesion { get; set; }
        public System.DateTime FechaIniciaSesion { get; set; }
        public Nullable<System.DateTime> FechaFinSesion { get; set; }
        public int OpcEstatusSesionUsuario { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<int> UsuarioAutorizaCierre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentaCobrarCliente> CuentaCobrarCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentaCobrarClienteMovimiento> CuentaCobrarClienteMovimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EfectivoEnResguardo> EfectivoEnResguardo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntregaEfectivo> EntregaEfectivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturaCliente> FacturaCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotaCargo> NotaCargo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotaCredito> NotaCredito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagoCliente> PagoCliente { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SesionCajaCierre> SesionCajaCierre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SesionFacturaEntrega> SesionFacturaEntrega { get; set; }
    }
}
