//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SesionUsuarioExterno
    {
        public System.Guid Id { get; set; }
        public System.Guid UsuarioExternoId { get; set; }
        public string SesionId { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<int> ClaveCanalVenta { get; set; }
    
        public virtual CanalVenta CanalVenta { get; set; }
    }
}
