//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudAnticipoProveedorAcreedor
    {
        public System.Guid AnticipoProveedorAcreedor_Id { get; set; }
        public System.Guid ProveedorAcreedor_Id { get; set; }
        public string SerieAnticipo { get; set; }
        public int FolioAnticipo { get; set; }
        public int ClaveSucursal { get; set; }
        public Nullable<System.Guid> PagoCuentaxPagar_Id { get; set; }
        public Nullable<int> ClaveOrdenCompraSucursal { get; set; }
        public Nullable<int> ClaveOrdenCompra { get; set; }
        public Nullable<System.Guid> OrdenCompra_Id { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public string Descripcion { get; set; }
        public int ClaveTipoMoneda { get; set; }
        public decimal ValorTipoCambio { get; set; }
        public decimal PorcentajeIVA { get; set; }
        public Nullable<decimal> PorcentajeIVACalculado { get; set; }
        public decimal ImporteSubTotal { get; set; }
        public decimal ImporteIVA { get; set; }
        public decimal ImporteTotal { get; set; }
        public decimal PorcentajeAnticipoProveedor { get; set; }
        public string NotaAnticipo { get; set; }
        public string NotaCancelacion { get; set; }
        public int Estatus { get; set; }
        public Nullable<int> UsuarioCancela { get; set; }
        public Nullable<System.DateTime> FechaCancela { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<int> UsuarioAutoriza1 { get; set; }
        public Nullable<System.DateTime> FechaAutoriza1 { get; set; }
        public Nullable<int> UsuarioAutoriza2 { get; set; }
        public Nullable<System.DateTime> FechaAutoriza2 { get; set; }
    
        public virtual ProveedorAcreedor ProveedorAcreedor { get; set; }
    }
}
