//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudCreditoRequisitoSeguimiento
    {
        public System.Guid SolicitudCredito_Id { get; set; }
        public Nullable<int> ClaveSolicitudCreditoRequisito { get; set; }
        public int ClaveRequisito { get; set; }
        public int OpcEstatusRequisito { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.Guid> ClienteDocumento_Id { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual ClienteDocumentos ClienteDocumentos { get; set; }
        public virtual ClienteSolicitudCredito ClienteSolicitudCredito { get; set; }
        public virtual SolicitudCreditoRequisito SolicitudCreditoRequisito { get; set; }
    }
}
