//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudChequeRequisito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SolicitudChequeRequisito()
        {
            this.SolicitudChequeRequisitoSeguimiento = new HashSet<SolicitudChequeRequisitoSeguimiento>();
        }
    
        public int ClaveSolicitudChequeRequisito { get; set; }
        public Nullable<int> ClaveTipoDocumentoCliente { get; set; }
        public int Secuencia { get; set; }
        public int OpcTipoSolicitud { get; set; }
        public string Descripcion { get; set; }
        public string Nota { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual TipoDocumentoCliente TipoDocumentoCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudChequeRequisitoSeguimiento> SolicitudChequeRequisitoSeguimiento { get; set; }
    }
}
