//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudEgreso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SolicitudEgreso()
        {
            this.SolicitudEgresoDocumento = new HashSet<SolicitudEgresoDocumento>();
        }
    
        public System.Guid SolicitudEgreso_Id { get; set; }
        public System.Guid ProveedorAcreedor_Id { get; set; }
        public string SerieEgreso { get; set; }
        public int FolioEgreso { get; set; }
        public int ClaveSucursalEgreso { get; set; }
        public string Documento { get; set; }
        public string Descripcion { get; set; }
        public int ClaveTipoMoneda { get; set; }
        public decimal ValorTipoCambio { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public decimal Subtotal { get; set; }
        public decimal ImporteIVA { get; set; }
        public decimal Total { get; set; }
        public decimal PorcentajeIVA { get; set; }
        public Nullable<decimal> PorcentajeIVACalculado { get; set; }
        public string NotaEgreso { get; set; }
        public string NotaCancelacion { get; set; }
        public int OpcTipoEgreso { get; set; }
        public int Estatus { get; set; }
        public Nullable<int> UsuarioCancela { get; set; }
        public Nullable<System.DateTime> FechaCancela { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<int> UsuarioAutoriza1 { get; set; }
        public Nullable<System.DateTime> FechaAutoriza1 { get; set; }
        public Nullable<int> UsuarioAutoriza2 { get; set; }
        public Nullable<System.DateTime> FechaAutoriza2 { get; set; }
    
        public virtual ProveedorAcreedor ProveedorAcreedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudEgresoDocumento> SolicitudEgresoDocumento { get; set; }
    }
}
