//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SucursalProductoExhibicion
    {
        public System.Guid SucursalProductoExhibicion_Id { get; set; }
        public System.Guid SucursalProducto_Id { get; set; }
        public string Notas { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public int ClaveTipo { get; set; }
        public int Estatus { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<System.Guid> ProveedorAcreedor_Id { get; set; }
        public Nullable<int> ClaveCategoria { get; set; }
        public Nullable<System.Guid> ExibicionUbicacion_Id { get; set; }
        public Nullable<int> UsuarioResponsable { get; set; }
    
        public virtual ExhibicionUbicacion ExhibicionUbicacion { get; set; }
        public virtual ProveedorAcreedor ProveedorAcreedor { get; set; }
        public virtual SucursalProducto SucursalProducto { get; set; }
    }
}
