//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SucursalAlmacenSeccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SucursalAlmacenSeccion()
        {
            this.InventarioFisicoControlFolios = new HashSet<InventarioFisicoControlFolios>();
            this.InventarioFisicoEmpleado = new HashSet<InventarioFisicoEmpleado>();
            this.InventarioFisicoProducto = new HashSet<InventarioFisicoProducto>();
            this.InventarioFisicoSeccionConteo = new HashSet<InventarioFisicoSeccionConteo>();
            this.InventarioFisicoUbicacion = new HashSet<InventarioFisicoUbicacion>();
            this.InventarioUbicacion = new HashSet<InventarioUbicacion>();
            this.SeccionProducto = new HashSet<SeccionProducto>();
            this.SeccionProductoBitacora = new HashSet<SeccionProductoBitacora>();
            this.SeccionProductoBitacora1 = new HashSet<SeccionProductoBitacora>();
        }
    
        public System.Guid SucursalAlmacenSeccion_Id { get; set; }
        public int ClaveSucursal { get; set; }
        public int ClaveAlmacen { get; set; }
        public int ClaveSeccion { get; set; }
        public string NombreSeccion { get; set; }
        public int ClaveEstatus { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual Almacen Almacen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventarioFisicoControlFolios> InventarioFisicoControlFolios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventarioFisicoEmpleado> InventarioFisicoEmpleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventarioFisicoProducto> InventarioFisicoProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventarioFisicoSeccionConteo> InventarioFisicoSeccionConteo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventarioFisicoUbicacion> InventarioFisicoUbicacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventarioUbicacion> InventarioUbicacion { get; set; }
        public virtual Seccion Seccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeccionProducto> SeccionProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeccionProductoBitacora> SeccionProductoBitacora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeccionProductoBitacora> SeccionProductoBitacora1 { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual SucursalAlmacenSeccionMapa SucursalAlmacenSeccionMapa { get; set; }
    }
}
