//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysPerfMon
    {
        public System.Guid SysPerfMon_Id { get; set; }
        public string Computadora { get; set; }
        public string Usuario { get; set; }
        public string Funcion { get; set; }
        public System.TimeSpan Tiempo { get; set; }
        public string Parametros { get; set; }
        public System.DateTime FechaAlta { get; set; }
    }
}
