//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehiculo()
        {
            this.ControlFolioReparto = new HashSet<ControlFolioReparto>();
        }
    
        public int ClaveVehiculo { get; set; }
        public Nullable<int> ClaveSucursal { get; set; }
        public bool Reparto { get; set; }
        public int ClaveTipoVehiculo { get; set; }
        public int ClaveMarcaVehiculo { get; set; }
        public string Placas { get; set; }
        public string Modelo { get; set; }
        public string Serie { get; set; }
        public string TipoEngomado { get; set; }
        public string NotaVehiculo { get; set; }
        public int OpcEstatusVehiculo { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlFolioReparto> ControlFolioReparto { get; set; }
        public virtual MarcaVehiculo MarcaVehiculo { get; set; }
        public virtual TipoVehiculo TipoVehiculo { get; set; }
    }
}
